language: node_js

node_js:
    - "10.16.3"

install:
    - npm install
    - npm install -g @angular/cli
script:
    - echo "skipping tests"
    - ng build --prod --base-href https://ZUP779.github.io/Angular-CITest/
    
deploy:
  provider: pages
  skip-cleanup: true 
  github-token: $TRAVISCITOKEN  # Set in travis-ci.org dashboard, marked secure https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: master