language: node_js

node_js:
    - "10.16.3"

install:
    - npm install
    - ng add angular-cli-ghpages
    
script:
    - echo "start ng deploy"
    - ng deploy --base-href=https://ZUP779.github.io/Angular-CITest/